name: refresh

on:
  workflow_dispatch:
  schedule: 
  - cron: "0 0,2,4,6,8,10,12,14,16,18,20,22 * * *"
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: checkout repo content
        uses: actions/checkout@v2 # checkout the repository content to github runner.
      - name: setup python
        uses: actions/setup-python@v2
        with:
          python-version: >3 #install the python needed
      - name: execute py script # run the run.py to get the latest data
        run: |
          sudo apt-get -y install python3-pip shadowsocks-libev
          pip install aiohttp aiohttp_socks
          python main.py ${{ secrets.git_token }} ${{ secrets.token }}
